server:
  port: 8080
fernando:
  url: http://pepe.com
  puerto: 8080
  pers:
    nombre: bruno
    apellido: diaz
    codigo: 1

lalista:
  personas:
  - nombre: maria
    apellido: corvalan
    codigo: 1
  - nombre: bruno
    apellido: diaz
    codigo: 2